language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: QKLb4i837lWc9qo326/jsPbCK1mZFHAnedbV8zKIXUOYNL2Hc11RAn7EPS7yZ1Pfg6/abX9ZWjXQoZ8si5S+1L76h3Oms+qRwIM2/BQlTPTa94xu6vO2HTMC0LyoZ4ee4EWkNt4WxgkfwOR4WnIoe43tqGDgPkb8Nrhcmd4NrrbyG2i79y0ChXysgw7T4SJIuXsoiZ1p3fQwHJD0RIoPvfmuk4wjylsEnPyLcUvhrHVOh4e3zUcEm68Ys9KBjFuALsN/dpblU8hP1qIjTZDhSkletSnr6n4JjDfbwzBP9OJTYXP9/bWHrYcD75IBATUNl38c/PYY3uGa7iuaDwWjQMvKIToIr5LBUkVfGnQxYGLZp+KnlauuABd5KgtkdfRVG6sZ+uNY0RxLwjsVEyk3deBnHBh4sxTrirr4i0X4wj9dJcAMvTklh0bQlDIyj03+haSarm9M6zNICJ5hgdh5eGDB6nL/AgO3P8X4FKB89JZJ9/Ql1wq7YyCmJIwyv1X+C37e5pZd19OCofPC3bR0QWskIlnc4ZEBdeL486R11gjbHPx7858xuNOe8n8co8DjKa07P+hkgjsXp0s09keofSA/1VtRsVsiAUwjUpgtg0348Yr9jJdXoSAYdX5e7EYQ7pRnzdbiAx4SMRwQjxYiBb9b2UOXYp/lxSuCEoStJmw=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: jejvCHm7W9bvIORt9hdaek4nwSsLJXHCagf2OKjr7JIVCn4o2rEQu6UA5tXV7YT5cIA6A2t5VfYV+iDyFXbZZrzdGO5MS9LdOQz4CPjtzpSNSAfMs43a7Uu1T17N+eVpBToUjgIeuLDEpm0jTIVbp5XkjWZnv1vxnt2E77VQl/dBU18N2Epgv4VuW6hpfFfacovWOVNK8KINDiZMXsgExNMttuWCM2SSjpJxjZUpV9667BZbgnOORibmWAwQ2QOST/xuwABTfZ9EPugHlnYTOVADpale7TCo+jIejTm7ErULwtroDbY+jfBjlvicD2viIcmmNXSE4GHy7rFLVw4MDwVsvSgmO7OVtOfu511FG1xsx6NUaUr1l8lFNDt/1SgliF9JGvalURaZUEGHq/el8ip72KgRzo9KV8hISU3td+3r6vNuLITmfQIPZACkDAJw3CPRoL5kn4Mr5WPRyYz0oWHATJpJPBXgoZrUwHhKBNq426A8x693nRG5CUaqYrxATCWGHAa+gchbijCZTOLXD8KZjyaQTQa+FRVopmEArtHEZ7G2nnsbupTgYQhTKqkz76V/8fwmOB0m3XRvSWHEN+jGmEoWSpXX5SnV75tKaGkZvBVfe8+P2qplthqBS85sRKyTlcYJ/YsXZw6YyZo/V1y8oGM+XvzmTC3UCD0kcY8=
  - secure: T8dTJIRpWBdxauOaKelL9n13wuAntcOWspO/Zhx+/fBPgdnhzTareSomQhDyf+78z+tM3KrL08YSAAYhFe5I896ZKVIOH7jS0tWO/Gz8jltYpt9qwiPgjUXPy4rHA6UWRt+APE2a+FIFbNoIPtn8sopi8KhGVChGmt80O0DGSrBIAvLg65T11FdbIP3lSvunB7tYXTFrm66iGOC8sh2ROBSqcvbizOI/B3Ee6sCXm5GZ53lLMyvR0rsCS/CIDAAVhc1yA+i1k6a01YgT0KSvl32mg0x/tg5b8mNqOSYVA2cuX6T5DKwlSWgDiAwoNO6oLrzZh/UWMyWBEfJaQ4YHglFESM5jAGvpiiVEFfuVqVQIBD5AkNbWJOPQszccwIvhhITNL4febivyKUaUN2vEMW2FUWvRJhNBbOBSYYzBTsCulNHSdTHJqujaNeLjS+jrzJZF/H1LvF2INymUBfNgAjDXskqLX9I/Iy6DMz6s42oRibXs30LvzSFdVIdFJnt5P3JWlfTbogySCTBjkcRU7MiTN3cGhRvobg5QVRwCTn5M5kfrBQZPAyRvXBPH1tmF9zV2HwOhokNKZZ+q1turQ52gwiDEf4zLVtu7gBPkmneMT57MRZXA6liGvdZulBz3GGolCeZ0+npFGy3A09qA48O/ApX1tljmcxEF+4Heogs=
  - secure: WPBcOeakSAWcymzuliSnp5Y+7lmsO9TC0U3XCwIuzygHle0Jfu8+2jXNMUXevaVeEEhpX2r1edPjObPcZ1nTsGns4GxkrgEyTvEGXUxElMjUVFlDCJ5a4ilJWY2iY4ShRaE2G5s+9dEtbf2sdZshuAEV4BeV+hp5P2CNnhTV/XJsxgcIORGoEKiSGlDbz5gX16oLR8H0J82kxt0TgXWUad2MnO+yVLDRDulhzLfE53YXQh4XFLi+UKIE357DM5E/Khvt4bR+ndnOD6Q5d9lL+EbcpOXqWRGXoix57V+vJo+kyW2k4hRSyqvYmLJVW3hOz1KzHoY1VKBrHHGGnjfrH3tugFt4nzJ8Xf1EM7AV4emza3iJQyJUzlwMDKAAA/jot+L3/IDkprWBF7d3ZGHZPVRcJEiy9NTjfTJigDb3p4+rtyaX3CfoUTom6TnFHYXfil7PKMH4+q9wTFzugnNhl2VK0EW9JU4ioEFR4BvCPuWBgLhFbyVDzzZwIfM5P8hpKRxaUw3TztXEcyKbDzgxrqGUzR3m+k3PjIhwL2OiGpEqwv9qtYHikKzDHL2rnkfupecZvViEMfLb7SbEdY+e1vtsaQnUA33eG4sWRPQsIj6wPR7jjyHP2o2PFs1Sh4WM9+F/uIdxa6aLcq1A7PcPywr6jLDIYZpO1rzBFp7NV+o=
before_install:
- openssl aes-256-cbc -K $encrypted_aaccab725bbc_key -iv $encrypted_aaccab725bbc_iv
  -in lof-ws-test-5c33f02ea8c8.json.enc -out ${TRAVIS_HOME}/lof-ws-test-5c33f02ea8c8.json -d
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=pub-dog-daemon-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_HOME}/lof-ws-test-5c33f02ea8c8.json
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
